name: askubuntu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel 
confinement: strict

apps:
  cli:
    command: cli
    environment:
      POSTS_XML: $SNAP/Posts.xml
      INDEX_DB: $SNAP/lookup.db
  api:
    command: api
    daemon: simple
    command-chain: [bin/get-configs]
    plugs: [network-bind]
    environment:
      POSTS_XML: $SNAP/Posts.xml
      INDEX_DB: $SNAP/lookup.db


parts:
  go-binaries:
    source: pkg
    plugin: go
    build-packages: [git, gcc]
    override-build: |
      cd cmd/cli
      go get -u 
      cd ../../
      cd cmd/api
      go get -u 

      cd ../../
      go build cmd/cli/cli.go
      go build cmd/api/api.go
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp cli api $SNAPCRAFT_PART_INSTALL/bin/

  static:
    source: static
    plugin: dump

  archive:
    plugin: dump
    source: https://archive.org/download/stackexchange/askubuntu.com.7z
    #source: archive
    build-packages: [p7zip-full, sqlite3, mawk]
    stage-packages: [sqlite3]
    override-build: |
      echo "question_id,id,start,length"> lookup.csv 
      mawk '{\
        line=$0;\
        foundmatch=match(line, / Id="[0-9]+/); \
        if(foundmatch){\
          id=substr( line, RSTART+5, RLENGTH-5); \
          questionid=id; \
          match(line, / ParentId="[0-9]+/); \
          parentid=substr( line, RSTART+11, RLENGTH-11); \
          if(parentid>=0){questionid=parentid}; \
          print questionid","id","start","1+length(line)\
        } \
        start=start+length(line)+1
      }' >> lookup.csv < Posts.xml 

      sqlite3 -csv lookup.db ".import lookup.csv posts"
      sqlite3 lookup.db 'CREATE INDEX question_id_index ON posts(question_id);'
      sqlite3 lookup.db 'UPDATE posts SET start = CAST(start AS NUMBER);'
      snapcraftctl build

    stage:
    - Posts.xml
    - lookup.db
    - usr
